# Generated by Django 5.0.3 on 2024-09-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
