# Generated by Django 5.0.3 on 2024-09-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_assignment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detailed_description',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
