# Generated by Django 5.0.3 on 2024-09-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_event_detailed_description_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentquestionanswer',
            name='max_score',
        ),
        migrations.AddField(
            model_name='question',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
    ]
